apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
- ../../iac/environments/dev2
patchesStrategicMerge:
  - flux-system/patch-kustomization-decryption.yaml
  - flux-system/patch-kustomize-env.yaml