apiVersion: apps/v1
kind: Deployment
metadata:
  name: squid
  namespace: squid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squid
  template:
    metadata:
      labels:
        app: squid
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: squid
          image: sameersbn/squid:latest
          ports:
            - containerPort: 3128
          volumeMounts:
            - name: squid-conf
              mountPath: /etc/squid
            - name: squid-cache
              mountPath: /var/spool/squid
      volumes:
        - name: squid-conf
          configMap:
            name: squid-config
        - name: squid-cache
          emptyDir: {}
