# clusters/my-k3s-cluster/apps/kube2iam/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube2iam
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kube2iam
      version: "2.5.0" # Убедитесь, что это актуальная версия чарта, если не 0.10.9
      sourceRef:
        kind: HelmRepository
        name: stable
        namespace: flux-system
  releaseName: kube2iam
  targetNamespace: kube-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    rbac:
      create: true
    host:
      ipAddressFromNode: false # ВАЖНОЕ ИЗМЕНЕНИЕ для On-Premise
      interface: cni0 # Проверьте, что это правильный интерфейс вашего узла K3s
    aws:
      region: ""
      accessKeyID: ""
      secretAccessKey: ""

    # *** УДАЛИТЕ ИЛИ ЗАКОММЕНТИРУЙТЕ СЕКЦИЮ extraArgs ОТСЮДА ***
    extraArgs:
#       - "--base-role-arn=arn:aws:iam::YOUR_AWS_ACCOUNT_ID:role/kube2iam-node-role-dummy"
       - "--iptables=true"
       - "--log-level=debug"

    env:
      - name: AWS_DEFAULT_REGION
        valueFrom:
          secretKeyRef:
            name: kube2iam-aws-credentials
            key: AWS_DEFAULT_REGION
      - name: AWS_ACCESS_KEY_ID
        valueFrom:
          secretKeyRef:
            name: kube2iam-aws-credentials
            key: AWS_ACCESS_KEY_ID
      - name: AWS_SECRET_ACCESS_KEY
        valueFrom:
          secretKeyRef:
            name: kube2iam-aws-credentials
            key: AWS_SECRET_ACCESS_KEY

#  # --- ДОБАВЬТЕ ЭТУ СЕКЦИЮ patches ---
#  patches:
#    - target:
#        kind: DaemonSet
#        name: kube2iam
#      patch: |
#        - op: replace
#          path: /spec/template/spec/containers/0/args
#          value:
#            - '--host-interface=cni0'
#            - '--node=$(NODE_NAME)'
#            - '--iptables=true' # Важно включить iptables
#            - '--base-role-arn=arn:aws:iam::YOUR_AWS_ACCOUNT_ID:role/kube2iam-node-role-dummy'
#            - '--log-level=debug'
#            - '--app-port=8181'
#            - '--metrics-port=8181'
#            # - '--no-daemon=false' # Этот флаг может быть избыточным, попробуйте без него сначала.
#                                  # Если будут проблемы с запуском (контейнер сразу завершается),
#                                  # попробуйте добавить '--no-daemon=true' сюда.