# clusters/my-k3s-cluster/flux-system/kube2iam-helm-repo.yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: stable
  namespace: flux-system
spec:
  interval: 1h
  url: https://charts.helm.sh/stable # Kube2IAM часто находится в этом репозитории