# clusters/my-k3s-cluster/infra/kube2iam/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: kube2iam
  namespace: kube-system
  labels:
    app.kubernetes.io/name: kube2iam
    app.kubernetes.io/instance: kube2iam
spec:
  type: ClusterIP
  ports:
    - port: 8181
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: kube2iam
    app.kubernetes.io/instance: kube2iam