# clusters/my-k3s-cluster/infra/kube2iam/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube2iam
  namespace: kube-system

---
# clusters/my-k3s-cluster/infra/kube2iam/clusterrole.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube2iam
rules:
  - apiGroups: [""] # "" указывает на основные ресурсы (pods, namespaces)
    resources: ["pods", "namespaces"]
    verbs: ["get", "list", "watch"] # Kube2IAM нужно читать эти ресурсы

---
# clusters/my-k3s-cluster/infra/kube2iam/clusterrolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube2iam
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube2iam # Имя ClusterRole, который мы создали выше
subjects:
  - kind: ServiceAccount
    name: kube2iam # Имя ServiceAccount, который использует под kube2iam
    namespace: kube-system # Пространство имен, где находится ServiceAccount