apiVersion: v1
data:
    token: ENC[AES256_GCM,data:bgNLMJ3Sk5ctX9wmU7mjQGmyoIPgX8t2I6SriTZZEg23K27PnUTb0xdc5r1NJyYDTdtK1NLHL4kodR55+j3zOg==,iv:g+ag+ngAyj2rMMIixv138W7H1B9bTrMd8RtTVDU5o64=,tag:Yy+obHn8rQMOqsP1tG8IvQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: kbot
sops:
    kms:
        - arn: arn:aws:kms:eu-west-1:682364461498:key/6b761dca-702a-4b5a-b995-be6302c81fe0
          created_at: "2025-07-11T21:45:21Z"
          enc: AQICAHgKX/kY1X2NV3dNANs1prn+ZBhtFE3CdD1OvIig21R9EwHAnecYz8eug7UUeUb7WME+AAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMkuRA0vqPnJUOLAIFAgEQgDvH6jbMVmSv5IonOaFuXcw4HTHkwdVGVBgSaNDxENvysM+Fven9EBIZXIplSOj/ZDD/0fGlTDsX8DZ2jg==
          aws_profile: ""
    lastmodified: "2025-07-11T21:45:21Z"
    mac: ENC[AES256_GCM,data:IxJY1vnwmgDbO8q3+y65URc4d0Ov28l0094C2NCuD+/ZkZzRbFU+xUCYc0VD5p0c5yW9Z3xQQr/mfd4jQwfsnq4wpIZ1mxlKxEbzX55vIYShsX10LAs31RaJ56cEdPOD0xoy5hJ/5uRHilzfl0m3dJ7J/ZTlHqhv7F0nTpPOs/c=,iv:iUfDYYbzN2qug14+IBBeQHRC/24mwRiuBEH0k5AK5eY=,tag:QsOoSzkhUuJ1pon4CcrmIQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
