name: Secret Scan

on:
  push:
#  pull_request:

jobs:
  gitleaks:
    name: Run Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks (print to log)
        run: |
          gitleaks detect --source . --verbose --no-git

      - name: Run Gitleaks with summary
        uses: gitleaks/gitleaks-action@v2
        with:
          args: detect --source . --report-format sarif --report-path gitleaks.sarif --exit-code 0
