name: Secret Scan

on:
  push:
#  pull_request:

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Gitleaks
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_$(uname -s)_$(uname -m).tar.gz | tar -xz
          sudo mv gitleaks /usr/local/bin/

      - name: Run Gitleaks (print to log)
        run: |
          echo "🔍 Running gitleaks scan..."
          gitleaks detect --source . \
            --exit-code 1 \
            --verbose \
            $(test -f .gitleaks.toml && echo "--config .gitleaks.toml" || true)
