name: Secret Scan
#version 1.0.1
on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  gitleaks-scan:
    name: Run Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Gitleaks manually
        run: |
          curl -sSL https://github.com/gitleaks/gitleaks/releases/latest/download/gitleaks_$(uname -s)_$(uname -m).tar.gz | tar -xz
          sudo mv gitleaks /usr/local/bin/

      - name: Run Gitleaks (generate report)
        run: |
          gitleaks detect --source . \
            --report-format sarif \
            --report-path gitleaks.sarif \
            --exit-code 0 \
            $(test -f .gitleaks.toml && echo "--config .gitleaks.toml" || true)

      - name: Print Gitleaks summary
        if: always()
        run: |
          echo "📋 Gitleaks summary:"
          if [ -f gitleaks.sarif ]; then
            jq -r '
              .runs[].results[] |
              "🔐 Rule: \(.ruleId)\n📄 File: \(.locations[0].physicalLocation.artifactLocation.uri):\(.locations[0].physicalLocation.region.startLine)\n"
            ' gitleaks.sarif || echo "✅ No leaks found"
          else
            echo "✅ No gitleaks.sarif file found"
          fi