name: Secret Scan
#version 1.0.1
on:
  push:
    branches:
      - '**'
  workflow_dispatch:

jobs:
  gitleaks-scan:
    name: Run Gitleaks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: --source=. --report-format sarif --report-path=gitleaks.sarif --exit-code=0

      - name: Run Gitleaks
        run: |
          gitleaks detect --source . --report-format sarif --report-path gitleaks.sarif --exit-code 1
      - name: Run Gitleaks (print to log)
        if: always()
        run: |
          echo "🔍 Running gitleaks scan..."
          gitleaks detect --source . \
            --exit-code 1 \
            --verbose \
            $(test -f .gitleaks.toml && echo "--config .gitleaks.toml" || true)